version: "3.9"
services:
  bot:
    container_name: meower-dev
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/home/node/
    user: "1000:1000"
    entrypoint: "npm run dev"
